# .NET Core Azure Pipeline for VPS Deployment

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  

# Define pipeline variables
variables:
  - group: Smart_Inventory_BE_Secrets

stages:
  - stage: Build
    displayName: 'Build the .NET Core app'
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK'
            inputs:
              packageType: 'sdk'
              version: '8.0.401'  # Use the version of .NET Core you're using

          - script: |
              dotnet restore
              dotnet build --configuration $(buildConfiguration)
              dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
            displayName: 'Restore, Build, and Publish the App'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'  
              includeRootFolder: false  
              archiveType: 'tar'
              archiveFile: '$(Build.ArtifactStagingDirectory)/SmartInventoryBE.tar.gz'  
              replaceExistingArchive: true

          # Step 5: Publish the tar as a pipeline artifact (optional)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/SmartInventoryBE.tar.gz'
              ArtifactName: 'SmartInventoryBE'
              publishLocation: 'Container'

